title: "Jiexiao Xu"
description: "Personal website and notes"
url: "https://jiexiaoxu.github.io"
baseurl: ""

permalink: /blog/:year/:month/:day/:title/
timezone: America/Los_Angeles

markdown: kramdown
kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
